#!/usr/bin/env bash
# Ping the IP address to passed as an argument

# Check if an argument is allowed
if [ -z "$1" ]; then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
  exit 1
fi

# Ping IP address 5 times
ping -c 5 "$1"